### ISSUE TITLE
Unknown CMake command "opensees_load"

### ISSUE THREAD

**Issue by yoyo-chen** [OpenSees/OpenSees#1082]
Hi OpenSees developers,

I am trying to build OpenSees 3.4.0 on a Win64 PC, following the OpenSees documents step by step. I have tried for a while and had some difficulties. 

(1) conan install .. --build missing --compiler.runtime="MT"
The above line produced this error:
conan install: error: unrecognized arguments: --compiler.runtime=MT
ERROR: Exiting with code: 2

(2) I tried to only input "conan install .. --build missing". Then I got the error about "zlib/1.2.12".
I have solved this error by the method shown in the following reply:
 https://github.com/OpenSees/OpenSees/issues/1052#issuecomment-1322426820

(3) cmake .. -DBLA_STATIC=ON -DMKL_LINK=static -DMKL_INTERFACE_FULL=intel_lp64 -DMUMPS_DIR="..\..\mumps\build"
Now I stack at this line. The outputs are shown below. The error is about the "Unknown CMake command "opensees_load"".

-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: C:/Program Files/OpenSees/build
CMake Error at BuildTools/cmake/OpenSeesDependenciesWin.cmake:26 (opensees_load):
  Unknown CMake command "opensees_load".
Call Stack (most recent call first):
  CMakeLists.txt:99 (include)

-------------------------------------------------------------------------------------------------------------------
BTW, I am building OpenSees 3.4.0 for use with OpenFresco 2.7.2...
I cannot find a workable combination of versions for OpenSees, OpenFresco, and Tcl by myself. 
I found this reply says that OpenFresco 2.7.2 will work with the latest OpenSees 3.4.0. 
https://github.com/OpenSees/OpenSees/issues/1038#issuecomment-1290000824
The OpenSees 3.4.0 Binary has not been released. So I am trying to build it from the source code.
However, it seems to be a long way to go for me...
Any help or suggestions about the above things will be greatly appreciated.

**Comment by yoyo-chen** [comment]
I pulled the current version of OpenSees and the above error disappeared.
But I got many new errors when running this line "cmake --build . --config Release --target OpenSees --parallel 4"

Here are the last lines of outputs showing errors:

69>libhdf5.lib(H5.obj) : error LNK2019: unresolved external symbol __imp__fdopen referenced in function H5_debug_mask
69>libhdf5.lib(H5system.obj) : error LNK2019: unresolved external symbol __imp__wremove referenced in function Wremove_utf8
69>libhdf5.lib(H5system.obj) : error LNK2019: unresolved external symbol __imp__putenv_s referenced in function Wsetenv
69>libhdf5.lib(H5system.obj) : error LNK2019: unresolved external symbol __imp__mktime64 referenced in function H5_make_time
69>tcl86tsx.lib(tclClock.obj) : error LNK2001: unresolved external symbol __imp__mktime64
69>libhdf5.lib(H5system.obj) : error LNK2019: unresolved external symbol __imp__getdrive referenced in function H5_build_extpath
69>libhdf5.lib(H5system.obj) : error LNK2019: unresolved external symbol __imp__getcwd referenced in function H5_build_extpath
69>libhdf5.lib(H5system.obj) : error LNK2019: unresolved external symbol __imp__getdcwd referenced in function H5_build_extpath
69>libhdf5.lib(H5Rint.obj) : error LNK2019: unresolved external symbol __imp__strdup referenced in function H5R__copy
69>libhdf5.lib(H5Zscaleoffset.obj) : error LNK2019: unresolved external symbol __imp_llround referenced in function H5Z_scaleoffset_precompress_fd
69>libhdf5.lib(H5Zscaleoffset.obj) : error LNK2019: unresolved external symbol __imp_llroundf referenced in function H5Z_scaleoffset_precompress_fd
69>libhdf5.lib(H5Zscaleoffset.obj) : error LNK2019: unresolved external symbol __imp_lroundf referenced in function H5Z_scaleoffset_precompress_fd
69>libhdf5.lib(H5Zscaleoffset.obj) : error LNK2019: unresolved external symbol __imp_roundf referenced in function H5Z_scaleoffset_precompress_fd
69>libhdf5.lib(H5FDsec2.obj) : error LNK2019: unresolved external symbol __imp__fstat64 referenced in function H5FD_sec2_open
69>libhdf5.lib(H5Clog_json.obj) : error LNK2019: unresolved external symbol __imp_setbuf referenced in function H5C_log_json_set_up
69>libhdf5.lib(H5Clog_trace.obj) : error LNK2001: unresolved external symbol __imp_setbuf
69>tcl86tsx.lib(tclBasic.obj) : error LNK2019: unresolved external symbol __imp__finite referenced in function ExprSqrtFunc
69>tcl86tsx.lib(tclUtil.obj) : error LNK2001: unresolved external symbol __imp__finite
69>tcl86tsx.lib(tclExecute.obj) : error LNK2001: unresolved external symbol __imp__finite
69>tcl86tsx.lib(tclStrToD.obj) : error LNK2001: unresolved external symbol __imp__finite
69>tcl86tsx.lib(tclBasic.obj) : error LNK2019: unresolved external symbol __imp_modf referenced in function ExprRoundFunc
69>tcl86tsx.lib(tclExecute.obj) : error LNK2001: unresolved external symbol __imp_modf
69>tcl86tsx.lib(tclWinTime.obj) : error LNK2019: unresolved external symbol __imp_tzset referenced in function TclpGetDate
69>tcl86tsx.lib(tclClock.obj) : error LNK2001: unresolved external symbol __imp_tzset
69>OLDNAMES.lib(tzset.obi) : error LNK2001: unresolved external symbol __imp_tzset
69>tcl86tsx.lib(tclWinTime.obj) : error LNK2019: unresolved external symbol __imp__ftime64 referenced in function NativeGetTime
69>tcl86tsx.lib(tclWinPipe.obj) : error LNK2019: unresolved external symbol __imp__stricmp referenced in function ApplicationType
69>tcl86tsx.lib(tclEnv.obj) : error LNK2001: unresolved external symbol __imp__stricmp
69>tcl86tsx.lib(tclWinFile.obj) : error LNK2001: unresolved external symbol __imp__stricmp
69>tcl86tsx.lib(tclWinPipe.obj) : error LNK2019: unresolved external symbol __imp_getpid referenced in function Tcl_PidObjCmd
69>OLDNAMES.lib(getpid.obi) : error LNK2001: unresolved external symbol __imp_getpid
69>tcl86tsx.lib(tclEnv.obj) : error LNK2019: unresolved external symbol __imp_putenv referenced in function EnvTraceProc
69>OLDNAMES.lib(putenv.obi) : error LNK2001: unresolved external symbol __imp_putenv
69>tcl86tsx.lib(tclWinFile.obj) : error LNK2019: unresolved external symbol __imp_wcsicmp referenced in function NativeIsExec
69>OLDNAMES.lib(wcsicmp.obi) : error LNK2001: unresolved external symbol __imp_wcsicmp
69>OLDNAMES.lib(putenv.obi) : error LNK2001: unresolved external symbol __imp__putenv
69>C:\Program Files\OpenSees-master\OpenSees\build\bin\OpenSees.exe : fatal error LNK1120: 23 unresolved externals
69>Done building project "OpenSees.vcxproj" -- FAILED.
========== Build: 68 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by fmckenna** [comment]
these linker errors are because the conan build was not done using the runtime "MT" option ..  the default conan build is the "MD" which is where all the missing symbols error messages are coming from as the cmake instruction is causing the code to be generated and linked with static libs .. post the settings file in your $HOME/.conan folder to show what runtime options are avail for your setup.

**Comment by yoyo-chen** [comment]
I see. Thank you Frank. The end of this post shows the settings.yml file in my $HOME/.canon folder. It does have the runtime "MT" option for Visual Studio. Besides, the conan version is 1.55.0-dev.

In addition, here is the configuration output when running "conan install .. --build missing" without the runtime option. As you said, the runtime is MD. 
---------------------------------------
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
-----------------------------------------



----------------------settings.yml starts from here-----------------------------------
# Only for cross building, 'os_build/arch_build' is the system that runs Conan
os_build: [Windows, WindowsStore, Linux, Macos, FreeBSD, SunOS, AIX, VxWorks]
arch_build: [x86, x86_64, ppc32be, ppc32, ppc64le, ppc64, armv5el, armv5hf, armv6, armv7, armv7hf, armv7s, armv7k, armv8, armv8_32, armv8.3, sparc, sparcv9, mips, mips64, avr, s390, s390x, sh4le, e2k-v2, e2k-v3, e2k-v4, e2k-v5, e2k-v6, e2k-v7]

# Only for building cross compilation tools, 'os_target/arch_target' is the system for
# which the tools generate code
os_target: [Windows, Linux, Macos, Android, iOS, watchOS, tvOS, FreeBSD, SunOS, AIX, Arduino, Neutrino]
arch_target: [x86, x86_64, ppc32be, ppc32, ppc64le, ppc64, armv5el, armv5hf, armv6, armv7, armv7hf, armv7s, armv7k, armv8, armv8_32, armv8.3, sparc, sparcv9, mips, mips64, avr, s390, s390x, asm.js, wasm, sh4le, e2k-v2, e2k-v3, e2k-v4, e2k-v5, e2k-v6, e2k-v7, xtensalx6, xtensalx106, xtensalx7]

# Rest of the settings are "host" settings:
# - For native building/cross building: Where the library/program will run.
# - For building cross compilation tools: Where the cross compiler will run.
os:
    Windows:
        subsystem: [None, cygwin, msys, msys2, wsl]
    WindowsStore:
        version: ["8.1", "10.0"]
    WindowsCE:
        platform: ANY
        version: ["5.0", "6.0", "7.0", "8.0"]
    Linux:
    iOS:
        version: &ios_version
                 ["7.0", "7.1", "8.0", "8.1", "8.2", "8.3", "9.0", "9.1", "9.2", "9.3", "10.0", "10.1", "10.2", "10.3",
                  "11.0", "11.1", "11.2", "11.3", "11.4", "12.0", "12.1", "12.2", "12.3", "12.4",
                  "13.0", "13.1", "13.2", "13.3", "13.4", "13.5", "13.6", "13.7",
                  "14.0", "14.1", "14.2", "14.3", "14.4", "14.5", "14.6", "14.7", "14.8",
                  "15.0", "15.1", "15.2", "15.3", "15.4", "15.5", "15.6", "16.0", "16.1"]
        sdk: [None, "iphoneos", "iphonesimulator"]
        sdk_version: [None, "11.3", "11.4", "12.0", "12.1", "12.2", "12.4",
                      "13.0", "13.1", "13.2", "13.4", "13.5", "13.6", "13.7",
                      "14.0", "14.1", "14.2", "14.3", "14.4", "14.5", "15.0", "15.2", "15.4", "15.5", "16.0", "16.1"]
    watchOS:
        version: ["4.0", "4.1", "4.2", "4.3", "5.0", "5.1", "5.2", "5.3", "6.0", "6.1", "6.2",
                  "7.0", "7.1", "7.2", "7.3", "7.4", "7.5", "7.6", "8.0", "8.1", "8.3", "8.4", "8.5", "8.6", "8.7", "9.0", "9.1"]
        sdk: [None, "watchos", "watchsimulator"]
        sdk_version: [None, "4.3", "5.0", "5.1", "5.2", "5.3", "6.0", "6.1", "6.2",
                      "7.0", "7.1", "7.2", "7.4", "8.0", "8.0.1", "8.3", "8.5", "9.0", "9.1"]
    tvOS:
        version: ["11.0", "11.1", "11.2", "11.3", "11.4", "12.0", "12.1", "12.2", "12.3", "12.4",
                  "13.0", "13.2", "13.3", "13.4", "14.0", "14.2", "14.3", "14.4", "14.5", "14.6", "14.7",
                  "15.0", "15.1", "15.2", "15.3", "15.4", "15.5", "15.6", "16.0", "16.1"]
        sdk: [None, "appletvos", "appletvsimulator"]
        sdk_version: [None, "11.3", "11.4", "12.0", "12.1", "12.2", "12.4",
                      "13.0", "13.1", "13.2", "13.4", "14.0", "14.2", "14.3", "14.5", "15.0", "15.2", "15.4", "16.0", "16.1"]
    Macos:
        version: [None, "10.6", "10.7", "10.8", "10.9", "10.10", "10.11", "10.12", "10.13", "10.14", "10.15", "11.0", "12.0", "13.0"]
        sdk: [None, "macosx"]
        sdk_version: [None, "10.13", "10.14", "10.15", "11.0", "11.1", "11.3", "12.0", "12.1", "12.3", "13.0"]
        subsystem:
            None:
            catalyst:
                ios_version: *ios_version
    Android:
        api_level: ANY
    FreeBSD:
    SunOS:
    AIX:
    Arduino:
        board: ANY
    Emscripten:
    Neutrino:
        version: ["6.4", "6.5", "6.6", "7.0", "7.1"]
    baremetal:
    VxWorks:
        version: ["7"]
arch: [x86, x86_64, ppc32be, ppc32, ppc64le, ppc64, armv4, armv4i, armv5el, armv5hf, armv6, armv7, armv7hf, armv7s, armv7k, armv8, armv8_32, armv8.3, sparc, sparcv9, mips, mips64, avr, s390, s390x, asm.js, wasm, sh4le, e2k-v2, e2k-v3, e2k-v4, e2k-v5, e2k-v6, e2k-v7, xtensalx6, xtensalx106, xtensalx7]
compiler:
    sun-cc:
        version: ["5.10", "5.11", "5.12", "5.13", "5.14", "5.15"]
        threads: [None, posix]
        libcxx: [libCstd, libstdcxx, libstlport, libstdc++]
    gcc: &gcc
        version: ["4.1", "4.4", "4.5", "4.6", "4.7", "4.8", "4.9",
                  "5", "5.1", "5.2", "5.3", "5.4", "5.5",
                  "6", "6.1", "6.2", "6.3", "6.4", "6.5",
                  "7", "7.1", "7.2", "7.3", "7.4", "7.5",
                  "8", "8.1", "8.2", "8.3", "8.4",
                  "9", "9.1", "9.2", "9.3", "9.4",
                  "10", "10.1", "10.2", "10.3",
                  "11", "11.1", "11.2", "11.3",
                  "12", "12.1", "12.2"]
        libcxx: [libstdc++, libstdc++11]
        threads: [None, posix, win32]  # Windows MinGW
        exception: [None, dwarf2, sjlj, seh]  # Windows MinGW
        cppstd: [None, 98, gnu98, 11, gnu11, 14, gnu14, 17, gnu17, 20, gnu20, 23, gnu23]
    Visual Studio: &visual_studio
        runtime: [MD, MT, MTd, MDd]
        version: ["8", "9", "10", "11", "12", "14", "15", "16", "17"]
        toolset: [None, v90, v100, v110, v110_xp, v120, v120_xp,
                  v140, v140_xp, v140_clang_c2, LLVM-vs2012, LLVM-vs2012_xp,
                  LLVM-vs2013, LLVM-vs2013_xp, LLVM-vs2014, LLVM-vs2014_xp,
                  LLVM-vs2017, LLVM-vs2017_xp, v141, v141_xp, v141_clang_c2, v142,
                  llvm, ClangCL, v143]
        cppstd: [None, 14, 17, 20, 23]
    msvc:
        version: [170, 180, 190, 191, 192, 193]
        update: [None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        runtime: [static, dynamic]
        runtime_type: [Debug, Release]
        cppstd: [98, 14, 17, 20, 23]
        toolset: [None, v110_xp, v120_xp, v140_xp, v141_xp]
    clang:
        version: ["3.3", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9", "4.0",
                  "5.0", "6.0", "7.0", "7.1",
                  "8", "9", "10", "11", "12", "13", "14", "15", "16"]
        libcxx: [None, libstdc++, libstdc++11, libc++, c++_shared, c++_static]
        cppstd: [None, 98, gnu98, 11, gnu11, 14, gnu14, 17, gnu17, 20, gnu20, 23, gnu23]
        runtime: [None, MD, MT, MTd, MDd, static, dynamic]
        runtime_type: [None, Debug, Release]
        runtime_version: [None, v140, v141, v142, v143]
    apple-clang: &apple_clang
        version: ["5.0", "5.1", "6.0", "6.1", "7.0", "7.3", "8.0", "8.1", "9.0", "9.1", "10.0", "11.0", "12.0", "13", "13.0", "13.1", "14", "14.0"]
        libcxx: [libstdc++, libc++]
        cppstd: [None, 98, gnu98, 11, gnu11, 14, gnu14, 17, gnu17, 20, gnu20, 23, gnu23]
    intel:
        version: ["11", "12", "13", "14", "15", "16", "17", "18", "19", "19.1"]
        update: [None, ANY]
        base:
            gcc:
                <<: *gcc
                threads: [None]
                exception: [None]
            Visual Studio:
                <<: *visual_studio
            apple-clang:
                <<: *apple_clang
    intel-cc:
        version: ["2021.1", "2021.2", "2021.3"]
        update: [None, ANY]
        mode: ["icx", "classic", "dpcpp"]
        libcxx: [None, libstdc++, libstdc++11, libc++]
        cppstd: [None, 98, gnu98, 03, gnu03, 11, gnu11, 14, gnu14, 17, gnu17, 20, gnu20, 23, gnu23]
        runtime: [None, static, dynamic]
        runtime_type: [None, Debug, Release]
    qcc:
        version: ["4.4", "5.4", "8.3"]
        libcxx: [cxx, gpp, cpp, cpp-ne, accp, acpp-ne, ecpp, ecpp-ne]
        cppstd: [None, 98, gnu98, 11, gnu11, 14, gnu14, 17, gnu17]
    mcst-lcc:
        version: ["1.19", "1.20", "1.21", "1.22", "1.23", "1.24", "1.25"]
        base:
            gcc:
                <<: *gcc
                threads: [None]
                exceptions: [None]

build_type: [None, Debug, Release, RelWithDebInfo, MinSizeRel]


cppstd: [None, 98, gnu98, 11, gnu11, 14, gnu14, 17, gnu17, 20, gnu20, 23, gnu23]  # Deprecated, use compiler.cppstd

**Comment by yoyo-chen** [comment]
I tried the following code (1) instead of (2), and it works. OpenSees was built successfully. But I don't know why (2) does not work on my pc.

(1) conan install .. --build missing --settings compiler.runtime="MT"
(2) conan install .. --build missing --compiler.runtime="MT"

**Comment by fmckenna** [comment]
thanks. i will add this to the documentation.

**Comment by ShenYiyao** [comment]
Excuse me, do you have opensees 3.4.0 exe files? Thank you.

**Comment by yoyo-chen** [comment]
> Excuse me, do you have opensees 3.4.0 exe files? Thank you.

yes, I have the 3.4.0 exe file.

**Comment by ShenYiyao** [comment]
Dear Chen, I am a master student from Beijing University of Technology, China. Could you please send me the opensees.exe 3.4.0 version ?  I've been trying for a long time, and it hasn't worked. Thank you very much.  My email is sshenyiyao@163.com  or shenyiyao@emails.bjut.edu.cn

**Comment by yoyo-chen** [comment]
Sure, I have sent it to both email addresses.

**Comment by ShenYiyao** [comment]
I got it. I tried it and It works. Thank you very much.

**Comment by Liu-ZA-81** [comment]
> > Excuse me, do you have opensees 3.4.0 exe files? Thank you.
> 
> yes, I have the 3.4.0 exe file.

Dear Chen, I am a postgraduate student at Hunan University, China. I have been attempting to compile OpenSees 3.4.0 myself but have encountered some difficulties. Could you kindly provide me with the OpenSees 3.4.0 executable file? I would greatly appreciate your assistance. My email is zaliu@hnu.edu.cn or liuza9481@gmail.com
