### ISSUE TITLE
Problems compiling on Linux HPC environment

### ISSUE THREAD

**Issue by chturner74** [OpenSees/OpenSees#153]
Hello,

I am working on compiling OpenSees v3.0.0 for my local HPC environment.  Have MUMPS 5.2.1 compiled with ParMETIS 4.0.3.  Have worked through a number of issues and have it down (I believe) to a final few issues associated with linking MUMPS/ParMETIS.  Upon the final linking for the OpenSeesMP binary, I get the following few errors:

```
/home/chturner/MUMPS_5.2.1/lib/libdmumps.a(dini_driver.o): In function `dmumps_ini_driver_':
dini_driver.F:(.text+0x2f6): undefined reference to `metis_setdefaultoptions_'
/home/chturner/MUMPS_5.2.1/lib/libmumps_common.a(ana_orderings_wrappers_m.o): In function `mumps_ana_ord_wrappers_mp_mumps_metis_nodend_mixedto32_':
ana_orderings_wrappers_m.F:(.text+0x35b): undefined reference to `metis_nodend_'
/home/chturner/MUMPS_5.2.1/lib/libmumps_common.a(ana_orderings_wrappers_m.o): In function `mumps_ana_ord_wrappers_mp_mumps_metis_nodend_mixedto64_':
ana_orderings_wrappers_m.F:(.text+0x56f): undefined reference to `metis_nodend_'
ana_orderings_wrappers_m.F:(.text+0xbd8): undefined reference to `metis_nodend_'
/home/chturner/MUMPS_5.2.1/lib/libmumps_common.a(mumps_metis.o): In function `mumps_parmetis_':
mumps_metis.c:(.text+0x26): undefined reference to `ParMETIS_V3_NodeND'
/home/chturner/MUMPS_5.2.1/lib/libmumps_common.a(mumps_metis.o): In function `mumps_metis_kway_':
mumps_metis.c:(.text+0x64): undefined reference to `METIS_SetDefaultOptions'
mumps_metis.c:(.text+0xca): undefined reference to `METIS_PartGraphKway'
```

In the Makefile.def, I have all of the MUMPS vars set as such:

```
MUMPS = YES
MUMPS_FLAG = -D_MUMPS
MUMPS_DIR = $(HOME)/MUMPS_5.2.1
MUMPS_LIB = -L$(MUMPS_DIR)/lib \
        $(FE)/system_of_eqn/linearSOE/mumps/MumpsSOE.o \
        $(FE)/system_of_eqn/linearSOE/mumps/MumpsSolver.o \
        $(FE)/system_of_eqn/linearSOE/mumps/MumpsParallelSOE.o \
        $(FE)/system_of_eqn/linearSOE/mumps/MumpsParallelSolver.o \
        -ldmumps \
        -lmumps_common \
        -lpord
MUMPS_INCLUDE = -I$(MUMPS_DIR)/include
```

No errors in compilation--just in the final linking.  Any ideas or suggestions? Thanks.

**Comment by chturner74** [comment]
I realize a lot of the developers here are Windows developers and the mention of Linux is probably a limiting factor on getting a response.  But any thoughts or suggestions would be appreciated.

I've tracked the issue down to a one .c file in the Metis code.  Specifically, metis-5.1.0/libmetis/frename.c (also in parmetis-4.0.3/metis/libmetis/frename.c).  I am not a C or FORTRAN guru, but as the comment on the file states, it "contains some renaming routines to deal with different Fortran compilers."  Each of the functions with an undefined reference in my error above is listed in this renaming file, frename.c.  What I don't understand is why MUMPS builds fine on its own (linking with Metis and ParMetis libraries), but the final linking for the OpenSeesMP binary has issues here.

And to be clear I am linking the Metis and ParMetis libraries immediately before the MUMPS library.  For example:

```
MUMPS_LIB = -L$(HOME)/OpenSees-build/parmetis-4.0.3/build/Linux-x86_64/libparmetis -lparmetis \
        -L$(HOME)/OpenSees-build/metis-5.1.0/build/Linux-x86_64/libmetis -lmetis \
        -L$(MUMPS_DIR)/lib -ldmumps -lmumps_common -lpord
```
So with that extra bit of detail in addition to my original post, does anyone have any ideas or suggestions?

Thanks!

**Comment by mhscott** [comment]
Closing. Try with CMake.
