### ISSUE TITLE
Issues in current CMakeLists.txt and their solutions

### ISSUE THREAD

**Issue by fslurrehman** [OpenSees/OpenSees#1101]
Hi, 

Current CMakeLists.txt `dated: 04-Jan-23` has several issues when compiling on windows and linux. However there is no problem on Mac. Following are the issues:

Windows Issues
------------------

WIndows has following two issues:

1-- OpenSeesMP Error for Intel MKL:

OpenSeesMP terminates without giving any error or solving the problem. However it sometimes gives following error:
    
`Intel MKL ERROR: Parameter 13 was incorrect on entry to DGEMM .`

This is because lapack and cmake is compiled with LP64 Interface while line 353 uses ILP64 Interface:
https://github.com/OpenSees/OpenSees/blob/de0be845deaab48e16f00f85d222c5ec032d4108/CMakeLists.txt#L353
                 
These libs needs to be replaced with lp64 by removing `i`. Then compile and OpenSeesMP will work fine. 

2-- OpenSeesSP Compilation Error:

OpenSeesSP gives compilation error as described in last comment of mine in #1051. This is because code is looking for Domain  class in several cpp files like myCommands.cpp while PartitionedDomain class is compiled. In order for code to look for PartitionedDomain class instead of Domain class, turn on the _PARALLEL_PROCESSING preprocessor for these files. by adding following lines in CMakeLists.txt after line 428 and before compilation of OPS_InterpTcl:
   
```
if(PARALLEL)
        message(STATUS "PARALLEL FOR SP TURNED ON ...")
        add_definitions(-D_PARALLEL_PROCESSING=1)
endif()
```    

Build cmake while adding -DPARALLEL=1 as:

`cmake .. -DBLA_STATIC=ON -DMKL_LINK=static -DMKL_INTERFACE_FULL=intel_lp64 -DMUMPS_DIR="..\..\mumps\build" -DPARALLEL=1 `

Then, compile for OpenSeesSP target twice as first run will give error while second run will pass. 

These steps will resolve both errors. OpenSeesMP and SP will work perfectly on windows as native executable. 

Linux Issues
-------------

1-- MPI and Sometimes Other Libs not Found
cmake on debian and ubuntu can't find OpenMPI. To resolve this issue add following lines in CMakeLists.txt after line 343 after else():
```
  set(MPI_C_INCLUDE_DIRS "/usr/lib/x86_64-linux-gnu/openmpi/include;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi" )
  set(MPI_CXX_LIBRARIES "/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so")
  set(MPI_Fortran_LIBRARIES "/usr/lib/x86_64-linux-gnu/libmpi_usempif08.so;/usr/lib/x86_64-linux-gnu/libmpi_usempi_ignore_tkr.so;/usr/lib/x86_64-linux-gnu/libmpi_mpifh.so;/usr/lib/x86_64-linux-gnu/libmpi.so;/usr/lib/x86_64-linux-gnu/libopen-rte.so;/usr/lib/x86_64-linux-gnu/libopen-pal.so;/usr/lib/x86_64-linux-gnu/libhwloc.so;/usr/lib/x86_64-linux-gnu/libevent_core.so;/usr/lib/x86_64-linux-gnu/libevent_pthreads.so;/usr/lib/x86_64-linux-gnu/libm.so;/home/<username>/.conan/data/zlib/1.2.12/_/_/package/<somenumber>/lib/libz.a")
  set(MPI_CXX_LINK_FLAGS "")
  set(MPI_FOUND TRUE)
  message(STATUS "MPI was found .. path added ${MPI_C_INCLUDE_DIRS} ${MPI_FOUND}")
  include_directories(SYSTEM ${MPI_C_INCLUDE_DIRS})
  if (NOT DEFINED MUMPS_DIR)
     set (MUMPS_FLAG -D_NOMUMPS)
     set (MUMPS_LIBRARIES "")
  else()
     set (MUMPS_FLAG -D_MUMPS)  
     if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
       set (MUMPS_LIBRARIES "${MUMPS_DIR}/dmumps;${MUMPS_DIR}/mumps_common;${MUMPS_DIR}/pord")
     else()
       set (MUMPS_LIBRARIES "${MUMPS_DIR}/libdmumps.a;${MUMPS_DIR}/libmumps_common.a;${MUMPS_DIR}/libpord.a")
       message("MUMPS DIR is ${MUMPS_DIR} and flag is ${MUMPS_FLAG}" )
     endif()
     

  endif()
  add_subdirectory("${PROJECT_SOURCE_DIR}/OTHER/SuperLU_DIST_4.3/SRC")
  add_subdirectory("${PROJECT_SOURCE_DIR}/OTHER/METIS") 

```
Don't forget to rename `<username>` and `<somenumber>` as per your installation for fortran libraries path in 3rd line above.

Also you need to add following flags in cmake build in case if lapack and/or python is not found or these libs are not `.so`

```
cmake .. -DLAPACK_LIBRARIES="/usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libmkl_gf_lp64.so;/usr/lib/x86_64-linux-gnu/libmkl_gnu_thread.so;/usr/lib/x86_64-linux-gnu/libmkl_core.so;/usr/lib/gcc/x86_64-linux-gnu/10/libgomp.so;-lm;-ldl" -DPython_INCLUDE_DIR="/usr/include/python3.10" -DPython_LIBRARY="/usr/lib/x86_64-linux-gnu/libpython3.10.so" -DPython_EXECUTABLE="/usr/bin/python3.10" -DMUMPS_DIR=$PWD/../../mumps/build -DOPENMPI=TRUE -DSCALAPACK_LIBRARIES="/usr/lib/x86_64-linux-gnu/libmkl_blacs_openmpi_lp64.so;/usr/lib/x86_64-linux-gnu/libscalapack-openmpi.so.2.1"

```

Rename the version of python as per your python installation in above python paths. 

2-- No CMakeLists.txt for OTHER/BLAS

On line 296 of CMakeLists.txt, Blas lib is added which requires CMakeLists.txt in OTHER/BLAS folder. However, when lapack is found, then this line won't run. 

By these steps, OpenSees with all targets will run on windows, linux and of course on Mac. 

Regards,
FR

**Comment by sunxiaoling** [comment]
Thanks for fixing the issue where I can't compile OpenseesSP under Windows 10. But there is a little problem with adopting your approach. I have solved this problem by adding following lines in CMakeLists.txt after line 430:
`if(PARALLEL)
        message(STATUS "PARALLEL FOR SP TURNED ON ...")
        target_compile_definitions(OPS_InterpTcl PUBLIC _PARALLEL_PROCESSING)
endif()`
Build cmake while adding -DPARALLEL=1 as:
cmake .. -DBLA_STATIC=ON -DMKL_LINK=static -DMKL_INTERFACE_FULL=intel_lp64 -DMUMPS_DIR="..\..\mumps\build" -DPARALLEL=1 
Then, I successfully compiled openseesSP.

**Comment by fslurrehman** [comment]
Hi @sunxiaoling:

Thanks for checking these steps. 

I faced no issue with steps I mentioned and compiled OpenSeesSP successfully. Today I checked them on fresh folders on line 430 as you suggested but found no change/improvement. I have same result as before. I haven't faced any compilation error.

However two things are important:
1.  Firstly compile the target of normal OpenSees using cmake build steps as per documentation. Then, paste those lines in CMakeLists.txt. Build it, then, compile OpenSeesSP target.  
2. At first cmake compile will fail but then on second trial, it will compile successfully. 

May be some libs are built by these 2 steps which are required for OpenSeesSP. I have checked OpenSeesSP binaries with example files and it works.

**Comment by GJoe2** [comment]
For the linux fix, I want to add something about zlib version

>   set(MPI_Fortran_LIBRARIES "/usr/lib/x86_64-linux-gnu/libmpi_usempif08.so;/usr/lib/x86_64-linux-gnu/libmpi_usempi_ignore_tkr.so;/usr/lib/x86_64-linux-gnu/libmpi_mpifh.so;/usr/lib/x86_64-linux-gnu/libmpi.so;/usr/lib/x86_64-linux-gnu/libopen-rte.so;/usr/lib/x86_64-linux-gnu/libopen-pal.so;/usr/lib/x86_64-linux-gnu/libhwloc.so;/usr/lib/x86_64-linux-gnu/libevent_core.so;/usr/lib/x86_64-linux-gnu/libevent_pthreads.so;/usr/lib/x86_64-linux-gnu/libm.so;/home/<username>/.conan/data/zlib/1.2.12/_/_/package/<somenumber>/lib/libz.a")

There is an version issue at this day (28/01/23) with zlib explained in [1052](https://github.com/OpenSees/OpenSees/issues/1052#issuecomment-1321205049), and its workaround is working with zlib 1.2.13, so I think this line code should be replaced with:

`
set(MPI_Fortran_LIBRARIES "/usr/lib/x86_64-linux-gnu/libmpi_usempif08.so;/usr/lib/x86_64-linux-gnu/libmpi_usempi_ignore_tkr.so;/usr/lib/x86_64-linux-gnu/libmpi_mpifh.so;/usr/lib/x86_64-linux-gnu/libmpi.so;/usr/lib/x86_64-linux-gnu/libopen-rte.so;/usr/lib/x86_64-linux-gnu/libopen-pal.so;/usr/lib/x86_64-linux-gnu/libhwloc.so;/usr/lib/x86_64-linux-gnu/libevent_core.so;/usr/lib/x86_64-linux-gnu/libevent_pthreads.so;/usr/lib/x86_64-linux-gnu/libm.so;/home/<username>/.conan/data/zlib/1.2.13/_/_/package/<somenumber>/lib/libz.a")
`
And Thanks for sharing your CMakeList.txt, I was stuck compiling OpenSeesMP and OpenSeesSP because of missing MPI libraries.

```
USING CONAN
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: /home/gjoe/OpenSees/build
-- Conan: Compiler GCC>=5, checking major version 11
-- Conan: Checking correct version: 11
-- Could NOT find MPI_C (missing: MPI_mpi_LIBRARY MPI_C_WORKS)
-- Could NOT find MPI_CXX (missing: MPI_mpi_cxx_LIBRARY MPI_mpi_LIBRARY MPI_CXX_WORKS)
-- Could NOT find MPI_Fortran (missing: MPI_mpi_usempif08_LIBRARY MPI_mpi_usempi_ignore_tkr_LIBRARY MPI_mpi_mpifh_LIBRARY MPI_mpi_LIBRARY MPI_open-rte_LIBRARY MPI_open-pal_LIBRARY MPI_Fortran_WORKS)
-- Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND MPI_Fortran_FOUND)
CMake Warning at CMakeLists.txt:286 (find_package):
  By not providing "FindMKL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "MKL", but
  CMake did not find one.

  Could not find a package configuration file provided by "MKL" with any of
  the following names:

    MKLConfig.cmake
    mkl-config.cmake

  Add the installation prefix of "MKL" to CMAKE_PREFIX_PATH or set "MKL_DIR"
  to a directory containing one of the above files.  If "MKL" provides a
  separate development package or SDK, be sure it has been installed.


-- LAPACK was found.
-- LAPACK_LINKER_FLAGS =
-- LAPACK_LIBRARIES = /usr/lib/x86_64-linux-gnu/liblapack.a;/usr/lib/x86_64-linux-gnu/libblas.a
Python_FOUND:TRUE
Python_VERSION:3.10.6
Python_Development_FOUND:TRUE
Python_LIBRARIES:/usr/lib/x86_64-linux-gnu/libpython3.10.a
Python_INCLUDES:/usr/include/python3.10
-- MPI was NOT found.
-- MKL NOT found .. user to provide -DSCALAPACK_LIBRARIES=
-- SCALAPACK_LIBRARIES=/usr/lib/x86_64-linux-gnu/libmkl_blacs_openmpi_lp64.so;/usr/lib/x86_64-linux-gnu/libscalapack-openmpi.so.2.1
OPS >>> Configuring OpenSees extensions
-- OPS >>> Have HDF5 and VERSION >= 1.12.0
-- Configuring done
-- Generating done
```
